#!/bin/bash
# Unattended finisher. Waits for any in-flight run_ablation.py, then completes
# every remaining analysis and writes ../RESULTS_SUMMARY.md.
#
#   caffeinate -i bash ~/Documents/RBP/run_overnight.sh
#
# Makes no choices that need you: every step uses the settings already agreed.
# Safe to run even if run_ablation.py has already finished. Everything is
# idempotent -- completed stages are detected and skipped.

set -u
cd "$(dirname "$0")/src" || exit 1
PY=$(command -v python3)
LOG="../overnight.log"
exec > >(tee -a "$LOG") 2>&1

echo "================================================================"
echo "overnight run started $(date)"
echo "================================================================"

# ---- 1. wait for any running ablation to finish -------------------------
while pgrep -f "run_ablation.py" > /dev/null; do
  echo "[$(date +%H:%M)] run_ablation.py still going, waiting 5 min..."
  sleep 300
done
echo "[$(date +%H:%M)] no ablation running"

# ---- 2. make sure all four 2x2 cells are complete -----------------------
echo
echo "== completing any missing 2x2 cells =="
$PY run_ablation.py || echo "WARNING: run_ablation.py returned non-zero"

# ---- 3. composition baseline for every dataset --------------------------
echo
echo "== composition-only baselines =="
rm -f ../outputs/composition_baseline.csv
for pair in \
  "../data/real_sequences.csv|D region negs + padded" \
  "../data/real_sequences_ablation_fixedcenter.csv|B region negs + centred" \
  "../data/real_sequences_cellA_chrom_centred.csv|A chrom negs + centred" \
  "../data/real_sequences_cellC_chrom_padded.csv|C chrom negs + padded" \
  "../data/real_sequences_v1_chromosome_negatives.csv|v1 original"
do
  f="${pair%%|*}"; lab="${pair##*|}"
  [ -f "$f" ] && $PY composition_baseline.py --data "$f" --label "$lab"
done

# ---- 4. causal motif-occlusion test on every cell ------------------------
echo
echo "== motif occlusion (causal test) =="
for pair in \
  "../data/real_sequences.csv|../outputs|D region negs + padded" \
  "../data/real_sequences_ablation_fixedcenter.csv|../outputs_ablation|B region negs + centred" \
  "../data/real_sequences_cellA_chrom_centred.csv|../outputs_cellA|A chrom negs + centred" \
  "../data/real_sequences_cellC_chrom_padded.csv|../outputs_cellC|C chrom negs + padded"
do
  d="${pair%%|*}"; rest="${pair#*|}"; m="${rest%%|*}"; lab="${rest##*|}"
  if [ -f "$d" ] && [ -d "$m" ]; then
    echo; echo "--- $lab ---"
    $PY motif_occlusion.py --data "$d" --model-dir "$m" --label "$lab" \
      || echo "WARNING: occlusion failed for $lab"
  fi
done

# ---- 5. regenerate figures from the final v2 data -----------------------
echo
echo "== regenerating figures =="
$PY generate_figures.py || echo "WARNING: figure generation failed"

# ---- 6. collect everything into one summary -----------------------------
echo
echo "== writing RESULTS_SUMMARY.md =="
$PY - <<'PYEOF'
import os, glob
import pandas as pd

R = os.path.join(os.path.dirname(os.path.abspath("..")), "")
def rd(p):
    return pd.read_csv(p) if os.path.exists(p) else None

lines = ["# Results summary", "", "Auto-generated by run_overnight.sh.", ""]

cells = [("A  chrom negs  + centred", "../outputs_cellA"),
         ("B  region negs + centred", "../outputs_ablation"),
         ("C  chrom negs  + padded",  "../outputs_cellC"),
         ("D  region negs + padded",  "../outputs")]

lines += ["## 2x2 design: attention motif localisation", "",
          "| cell | hit rate | seed SD | null | AUC-ROC |", "|---|---|---|---|---|"]
store = {}
for name, d in cells:
    v = rd(os.path.join(d, "pum2_motif_validation.csv"))
    r = rd(os.path.join(d, "results_log.csv"))
    if v is None:
        lines.append(f"| {name} | not run | | | |"); continue
    h = v.all_hit_rate_given_motif
    store[name] = h.values
    auc = ""
    if r is not None:
        rr = r[r.model == "cnn_lstm_attention"].drop_duplicates("seed")
        auc = f"{rr.test_auc_roc.mean():.4f}"
    lines.append(f"| {name} | {h.mean():.3f} | {h.std(ddof=1):.3f} | "
                 f"{v.all_null_hit_rate_given_motif.mean():.3f} | {auc} |")
lines.append("| v1 (superseded, different BED) | 0.359 | 0.152 | 0.127 | 0.8206 |")
lines.append("")

if len(store) == 4:
    A, B, C, D = (store[n] for n, _ in cells)
    lines += ["### Main effects", "",
              f"- region-matched negatives: {((B.mean()+D.mean())-(A.mean()+C.mean()))/2:+.3f}",
              f"- random-padded positives: {((C.mean()+D.mean())-(A.mean()+B.mean()))/2:+.3f}",
              f"- interaction: {(D.mean()-C.mean())-(B.mean()-A.mean()):+.3f}", ""]

cb = rd("../outputs/composition_baseline.csv")
if cb is not None:
    lines += ["## Composition-only baseline", "", "| dataset | AUC-ROC | AUC-PR |", "|---|---|---|"]
    lines += [f"| {r.dataset} | {r.auc_roc:.4f} | {r.auc_pr:.4f} |" for r in cb.itertuples()]
    lines.append("")

occ = [f for f in glob.glob("../outputs*/motif_occlusion.csv")]
if occ:
    lines += ["## Motif occlusion (causal test)", "",
              "| cell | p original | motif shuffled | control shuffled | excess drop |",
              "|---|---|---|---|---|"]
    for f in sorted(occ):
        d = pd.read_csv(f)
        lines.append(f"| {d.cell.iloc[0]} | {d.p_original.mean():.3f} | "
                     f"{d.p_motif_shuffled.mean():.3f} | {d.p_control_shuffled.mean():.3f} | "
                     f"{d.excess_drop.mean():+.4f} |")
    lines.append("")

ig = rd("../outputs/pum2_ig_validation_full.csv")
at = rd("../outputs/pum2_motif_validation.csv")
if ig is not None and at is not None:
    lines += ["## Attention vs IG on the final dataset (cell D)", "",
              f"- attention hit rate: {at.all_hit_rate_given_motif.mean():.3f} "
              f"± {at.all_hit_rate_given_motif.std(ddof=1):.3f}",
              f"- IG hit rate: {ig.ig_hit_rate_given_motif.mean():.3f} "
              f"± {ig.ig_hit_rate_given_motif.std(ddof=1):.3f}",
              f"- attention/IG agreement: {ig.attn_ig_agreement_rate.mean():.3f} "
              f"± {ig.attn_ig_agreement_rate.std(ddof=1):.3f}", ""]

full = rd("../outputs/results_log.csv")
if full is not None:
    lines += ["## Classification, final dataset, all three architectures", "",
              "| model | AUC-ROC | AUC-PR |", "|---|---|---|"]
    for m in ["baseline", "cnn_lstm", "cnn_lstm_attention"]:
        s = full[full.model == m].drop_duplicates("seed")
        if len(s):
            lines.append(f"| {m} | {s.test_auc_roc.mean():.4f} ± {s.test_auc_roc.std(ddof=1):.4f} "
                         f"| {s.test_auc_pr.mean():.4f} ± {s.test_auc_pr.std(ddof=1):.4f} |")
    lines.append("")

open("../RESULTS_SUMMARY.md", "w").write("\n".join(lines) + "\n")
print("wrote ../RESULTS_SUMMARY.md")
PYEOF

echo
echo "================================================================"
echo "overnight run finished $(date)"
echo "Open RESULTS_SUMMARY.md, or paste it to Claude to write the paper."
echo "================================================================"
